### ISSUE TITLE
BEEmaker used to refused to open. Cannot delete it.

### ISSUE THREAD

**Issue by ghost** [seagemgames/BEEmaker#8]
When I downloaded it, it won't able to run. It's giving me a "unable to find a require item" error. Because of this, I tried to delete it, but it won't as I require permissions from my computer to change it. Somehow, it was able to run it, but it doesn't change the fact that I cannot delete it.

![image](https://user-images.githubusercontent.com/55925854/104657261-44836400-5686-11eb-8567-f632dc07816b.png)

Why is this the case, and do anyone know how to remove it?

**Comment by saismeesaimonsaimes** [comment]
Try restarting your computer and deleting it again. Also, I've uploaded a new version that should fix it.

**Comment by saismeesaimonsaimes** [comment]
Fixed after a reboot.

**Comment by ghost** [comment]
Thanks!
